### ISSUE TITLE
restify.com homepage meta-tag content and favicon

### ISSUE THREAD

**Issue by polynomialherder** [restify/restify.github.io#5]
Google indexes restify.com with the following description in search results:

> Jekyll Template for Project Websites providing documentation and blog post pages.

This is because of the content attribute of the meta tag on the home page:

`<meta name="description" content="Jekyll Template for Project Websites providing documentation and blog post pages.">`

Further, the favicon is the default Jekyll icon. 
 
I realize this is not the repository for the website, but the template, but it seemed the best place to mention it -- apologies if that isn't the case.

**Comment by lukemcgregor** [comment]
#6 fixes the issue with the meta description

**Comment by retrohacker** [comment]
Thanks for opening an issue @affinespaces, this is def the place to report things like this :heart:

Fixed in #10 and #11
